blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/redhat-developer/design-manual/issues/new?labels=question&template=general-questions.md&title=%5BQUESTION%5D
    about: Please ask and answer questions here.
  - name: Design Manual Bug Reports
    url: https://github.com/redhat-developer/design-manual/blob/main/.github/ISSUE_TEMPLATE/bug_report.md
    about: Please report any bugs or issues here.
  - name: Design Manual Security Vulnerbality Reports
    url: https://github.com/redhat-developer/design-manual/issues/new?assignees=mindreeper2420&labels=security&template=security-report.md&title=%5BSECURITY%5D
    about: Please report security vulnerabilities here.
