# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  repo: redhat-developer/design-manual
  branch: master # Branch to update (master by default)
  squash_merges: true
  commit_messages:
    create: Create "{{slug}}" page
    update: Update "{{slug}}" page
    delete: Delete "{{slug}}" page
    uploadMedia: Upload "{{path}}"
    deleteMedia: Delete "{{path}}"

logo_url: https://redhat-developer.github.io/design-manual/assets/img/NewRHDFullLogo_black.png
publish_mode: editorial_workflow # Enable drafts
media_folder: "assets/uploads" # Folder where user uploaded files should go
pull_request_url: https://github.com/redhat-developer/design-manual/pulls

collections: # A list of collections the CMS should be able to edit
  # PAGES
  - name: "page"
    label: "Overview Pages"
    folder: "pages"
    sort: "title:asc"
    create: true # Allow users to create new Overview Pages in the admin UI
    delete: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "select"
        hint: "Select a layout to use."
        options:
          - { label: "Getting Started", value: "getting-started" }
          - { label: "Designer pages", value: "design" }
          - { label: "Developer pages", value: "develop" }
          - { label: "Creator pages", value: "create" }
          - { label: "About pages", value: "page" }
        required: true
      - label: "Category"
        name: "category"
        widget: "select"
        hint: "Select a category to use - should match primary nav that this page will reside under."
        options:
          - { label: "Getting Started", value: "getting-started" }
          - { label: "Designer pages", value: "design" }
          - { label: "Developer pages", value: "develop" }
          - { label: "Creator pages", value: "create" }
          - { label: "About pages", value: "page" }
        required: true
      - label: "Section"
        name: "section"
        widget: "string"
        hint: "This should match the sidenav parent item."
        required: false
      - label: "URL"
        name: "permalink"
        widget: "string"
        default: "/{{category}}/{{page-title}}"
        hint: "If applicable, replace {{page-title}} with the title of the page"
        required: true
      - label: "Title"
        name: "title"
        widget: "string"
        hint: "The title of the page"
        tagname: "h1"
        required: true
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: true}
  - name: "getting-started"
    label: "Getting Started Pages"
    folder: "pages/getting-started"
    sort: "title:asc"
    create: true # Allow users to create new Getting Started pages in the admin UI
    delete: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "getting-started"
        required: true
      - label: "Category"
        name: "category"
        widget: "select"
        hint: "Select a category to use - should match primary nav that this page will reside under."
        options:
          - { label: "Getting Started", value: "getting-started" }
          - { label: "Designer pages", value: "design" }
          - { label: "Developer pages", value: "develop" }
          - { label: "Creator pages", value: "create" }
          - { label: "About pages", value: "page" }
        required: true
      - label: "Section"
        name: "section"
        widget: "string"
        hint: "This should match the sidenav parent item."
        required: false
      - label: "URL"
        name: "permalink"
        widget: "string"
        default: "/{{category}}/{{page-title}}"
        hint: "If applicable, replace {{page-title}} with the title of the page"
        required: true
      - label: "Title"
        name: "title"
        widget: "string"
        hint: "The title of the page"
        tagname: "h1"
        required: true
      - label: "Intro Paragraph"
        name: "intro_paragraph"
        widget: "markdown"
        required: false
      - label: "Custom JS File"
        name: "custom_js"
        widget: "string"
        default: ""
        hint: "Add a custom JS file to the page."
        required: false
      - label: "Custom CSS File"
        name: "custom_css"
        widget: "string"
        default: ""
        hint: "Add a custom CSS file to the page."
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: true
  - name: "design"
    label: "Design Pages"
    folder: "pages/design"
    sort: "title:asc"
    create: true # Allow users to create new Design pages in the admin UI
    delete: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "design"
        required: true
      - label: "Category"
        name: "category"
        widget: "select"
        hint: "Select a category to use - should match primary nav that this page will reside under."
        options:
          - { label: "Getting Started", value: "getting-started" }
          - { label: "Designer pages", value: "design" }
          - { label: "Developer pages", value: "develop" }
          - { label: "Creator pages", value: "create" }
          - { label: "About pages", value: "page" }
        required: true
      - label: "Section"
        name: "section"
        widget: "string"
        hint: "This should match the sidenav parent item. If a parent item, leave blank."
        tagname: "h3"
        required: false
      - label: "URL"
        name: "permalink"
        widget: "string"
        default: "/{{category}}/{{page-title}}"
        hint: "If applicable, replace {{page-title}} with the title of the page"
        required: true
      - label: "Title"
        name: "title"
        widget: "string"
        hint: "The title of the page"
        tagname: "h4"
        required: true
      - label: "Intro Paragraph"
        name: "intro_paragraph"
        widget: "markdown"
        required: false
      - label: "Custom JS File"
        name: "custom_js"
        widget: "string"
        default: ""
        hint: "Add a custom JS file to the page."
        required: false
      - label: "Custom CSS File"
        name: "custom_css"
        widget: "string"
        default: ""
        hint: "Add a custom CSS file to the page."
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: true
  - name: "develop"
    label: "Develop Pages"
    folder: "pages/develop"
    sort: "title:asc"
    create: true # Allow users to create new Design pages in the admin UI
    delete: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "develop"
        required: true
      - label: "Category"
        name: "category"
        widget: "select"
        hint: "Select a category to use - should match primary nav that this page will reside under."
        options:
          - { label: "Getting Started", value: "getting-started" }
          - { label: "Designer pages", value: "design" }
          - { label: "Developer pages", value: "develop" }
          - { label: "Creator pages", value: "create" }
          - { label: "About pages", value: "page" }
        required: true
      - label: "Section"
        name: "section"
        widget: "string"
        hint: "This should match the sidenav parent item. If a parent item, leave blank."
        tagname: "h3"
        required: false
      - label: "URL"
        name: "permalink"
        widget: "string"
        default: "/{{category}}/{{page-title}}"
        hint: "If applicable, replace {{page-title}} with the title of the page"
        required: true
      - label: "Title"
        name: "title"
        widget: "string"
        hint: "The title of the page"
        tagname: "h4"
        required: true
      - label: "Intro Paragraph"
        name: "intro_paragraph"
        widget: "markdown"
        required: false
      - label: "Custom JS File"
        name: "custom_js"
        widget: "string"
        default: ""
        hint: "Add a custom JS file to the page."
        required: false
      - label: "Custom CSS File"
        name: "custom_css"
        widget: "string"
        default: ""
        hint: "Add a custom CSS file to the page."
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: true
  - name: "create"
    label: "Create Pages"
    folder: "pages/create"
    sort: "title:asc"
    create: true # Allow users to create new Design pages in the admin UI
    delete: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "pages"
        required: true
      - label: "Category"
        name: "category"
        widget: "select"
        hint: "Select a category to use - should match primary nav that this page will reside under."
        options:
          - { label: "Getting Started", value: "getting-started" }
          - { label: "Designer pages", value: "design" }
          - { label: "Developer pages", value: "develop" }
          - { label: "Creator pages", value: "create" }
          - { label: "About pages", value: "page" }
        required: true
      - label: "Section"
        name: "section"
        widget: "string"
        hint: "This should match the sidenav parent item. If a parent item, leave blank."
        tagname: "h3"
        required: false
      - label: "URL"
        name: "permalink"
        widget: "string"
        default: "/{{category}}/{{page-title}}"
        hint: "If applicable, replace {{page-title}} with the title of the page"
        required: true
      - label: "Title"
        name: "title"
        widget: "string"
        hint: "The title of the page"
        tagname: "h4"
        required: true
      - label: "Intro Paragraph"
        name: "intro_paragraph"
        widget: "markdown"
        required: false
      - label: "Custom JS File"
        name: "custom_js"
        widget: "string"
        default: ""
        hint: "Add a custom JS file to the page."
        required: false
      - label: "Custom CSS File"
        name: "custom_css"
        widget: "string"
        default: ""
        hint: "Add a custom CSS file to the page."
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: true
  - name: "pages"
    label: "Page Example Pages"
    folder: "pages/pages"
    sort: "title:asc"
    create: true # Allow users to create new Page example pages in the admin UI
    delete: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "pages"
        required: true
      - label: "Title"
        name: "title"
        widget: "string"
        hint: "The title and link to the page"
        tagname: "h4"
        required: true
      - label: "Category"
        name: "category"
        widget: "string"
        hint: "Page category - matches what dropdown it should appear under"
        tagname: "h3"
        required: true
      - label: "URL"
        name: "permalink"
        widget: "string"
        default: "/{{page-title}}"
        hint: "If applicable, replace {{page-title}} with the title of the page"
        required: true
      - label: "Custom JS File"
        name: "custom_js"
        widget: "string"
        default: ""
        hint: "Add a custom JS file to the page."
        required: false
      - label: "Custom CSS File"
        name: "custom_css"
        widget: "string"
        default: ""
        hint: "Add a custom CSS file to the page."
        required: false
      - label: "Section"
        name: "section"
        widget: "select"
        hint: "The area (section) where this page will live"
        options:
          - { label: "Example pages", value: "pages" }
          - { label: "Design pages", value: "design" }
          - { label: "Getting Started", value: "getting-started" }
          - { label: "Assembly Examples", value: "assemblies" }
          - { label: "About pages", value: "page" }
        required: true
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: true}
  # Navigation
  - name: "options"
    label: "Navigations"
    delete: false
    editor:
      preview: false
    files:
      - name: "assemblies"
        label: "Assemblies Page Navigation"
        file: "_data/assemblies.yml"
        description: "Used for creating the vertival navigation on Assembly example pages."
        fields:
          - name: "toc"
            label: "Assemblies"
            widget: "list"
            fields:
              subfolderitems:
                - { label: "Page", name: page, widget: string }
                - { label: "URL", name: url, widget: string }
      - label: "Components Navigation"
        name: "components-nav"
        file: "_data/components.yml"
        fields:
          - label: "Components Items"
            name: "toc"
            widget: "list"
            fields:
              - {label: "Page", name: page, widget: string}
              - {label: "URL", name: url, widget: string}
      - label: "Create section navigation"
        name: "create-nav"
        file: "_data/create.yml"
        fields:
          - label: "Create vertical navigation items"
            name: "toc"
            widget: "list"
            fields:
              - {label: "Page", name: page, widget: string}
              - {label: "URL", name: url, widget: string}
      - label: "Design section navigation"
        name: "design-nav"
        file: "_data/design.yml"
        fields:
          - label: "Design vertical navigation items"
            name: "toc"
            widget: "list"
            fields:
              - {label: "Page", name: page, widget: string}
              - {label: "URL", name: url, widget: string}
      - label: "Develop section navigation"
        name: "develop-nav"
        file: "_data/develop.yml"
        fields:
          - label: "Develop vertical navigation items"
            name: "toc"
            widget: "list"
            fields:
              - {label: "Page", name: page, widget: string}
              - {label: "URL", name: url, widget: string}
      - label: "Getting Started section navigation"
        name: "getting-started-nav"
        file: "_data/getting-started.yml"
        fields:
          - label: "Getting Started vertical navigation items"
            name: "toc"
            widget: "list"
            fields:
              - {label: "Page", name: page, widget: string}
              - {label: "URL", name: url, widget: string}
      - label: "Homepage section for Creator Quick Links"
        name: "quick_links-creator"
        file: "_data/quick_links-creator.yml"
        fields:
          - label: "Creator quick links"
            name: "toc"
            widget: "list"
            fields:
              - {label: "Page", name: page, widget: string}
              - {label: "URL", name: url, widget: string}
      - label: "Homepage section for Designer Quick Links"
        name: "quick_links-designer"
        file: "_data/quick_links-designer.yml"
        fields:
          - label: "Designer quick links"
            name: "toc"
            widget: "list"
            fields:
              - {label: "Page", name: page, widget: string}
              - {label: "URL", name: url, widget: string}
      - label: "Homepage section for Developer Quick Links"
        name: "quick_links-developer"
        file: "_data/quick_links-developer.yml"
        fields:
          - label: "Developer quick links"
            name: "toc"
            widget: "list"
            fields:
              - {label: "Page", name: page, widget: string}
              - {label: "URL", name: url, widget: string}
